index:
  title: Slides
slides:
  # https://revealjs.com/themes/
  theme: white #night
  highlight_theme: vs
  separator_vertical: ^\s*-v-\s*$
revealjs: # https://revealjs.com/config/
  height: 1080
  width: 1920
  navigationMode: linear
  slideNumber: true
  transition: slide
